version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - '19336:19336'
    user: '1000'
    command: ["yarn", "develop", "--host", "0.0.0.0"]
